param(
    [Parameter(Mandatory = $true)]
    [string]$HbcPath,
    [Parameter(Mandatory = $true)]
    [string]$OutputCPath
)

$ErrorActionPreference = "Stop"

if (!(Test-Path -LiteralPath $HbcPath)) {
    throw "HBC file not found: $HbcPath"
}

$outputDir = Split-Path -Parent $OutputCPath
if (![string]::IsNullOrWhiteSpace($outputDir) -and !(Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$bytes = [System.IO.File]::ReadAllBytes($HbcPath)
if ($bytes.Length -eq 0) {
    throw "HBC file is empty: $HbcPath"
}

$hexBytes = foreach ($b in $bytes) { ("0x{0:X2}" -f $b) }
$lineWidth = 12
$lines = for ($i = 0; $i -lt $hexBytes.Count; $i += $lineWidth) {
    $end = [Math]::Min($i + $lineWidth - 1, $hexBytes.Count - 1)
    "    " + (($hexBytes[$i..$end] -join ", ") + ",")
}
$byteBlock = ($lines -join "`r`n")

$content = @"
/* vm_program_data.c -- auto-generated from .hbc */

#include "vm_program.h"

/* Auto-generated by tools/update_vm_program_data.ps1 */
const uint8_t g_vm_program[] = {
$byteBlock
};

const uint32_t g_vm_program_size = sizeof(g_vm_program);
"@

[System.IO.File]::WriteAllText($OutputCPath, ($content + "`r`n"), [System.Text.Encoding]::ASCII)
Write-Host "Updated:" $OutputCPath
Write-Host "Bytes:" $bytes.Length
